/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import analizadorLexico_controlador.AnalizadorLexico;
import analizadorLexico_controlador.CargadorArchivo;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import analizadorLexico_modelo.ErrorLexico;
import analizadorLexico_modelo.Lexema;
import analizadorSemantico_controlador.AnalizadorSemantico;
import analizadorSintactico_controlador.AnalizadorSintactico;
import analizadorSintactico_modelo.sentencias.Archivo;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author diegoul818
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    CargadorArchivo cargar;
    AnalizadorLexico analizadorLexico;
    AnalizadorSintactico analizadorSintactico;
    JFileChooser seleccionar = new JFileChooser();
    File archivo;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cargar = new CargadorArchivo();
        analizadorLexico = new AnalizadorLexico();
        analizadorSintactico = new AnalizadorSintactico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        btnCorrer = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        arbolDerivacion = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTALexico = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lexemas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnAbrir.setBackground(new java.awt.Color(255, 255, 255));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/abrir.PNG"))); // NOI18N
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnCorrer.setBackground(new java.awt.Color(255, 255, 255));
        btnCorrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/correr.PNG"))); // NOI18N
        btnCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnCorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorrer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane4.setViewportView(arbolDerivacion);

        jSplitPane1.setLeftComponent(jScrollPane4);

        jTALexico.setColumns(20);
        jTALexico.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTALexico.setRows(5);
        jTALexico.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTALexico.setSelectionColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTALexico);

        jSplitPane1.setRightComponent(jScrollPane1);

        jSplitPane2.setTopComponent(jSplitPane1);

        jTabbedPane1.setToolTipText("");

        jPanel2.setFont(new java.awt.Font("Source Code Pro Light", 0, 12)); // NOI18N

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane3.setViewportView(consola);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consola", jPanel2);

        lexemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(lexemas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lexemas", jPanel1);

        jSplitPane2.setBottomComponent(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        if (cargar.seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            cargar.archivo = cargar.seleccionar.getSelectedFile();
            if (cargar.archivo.canRead()) {
                if (cargar.archivo.getName().endsWith("")) {
                    String documento = cargar.CargarArchivo(cargar.archivo);
                    jTALexico.setText(documento);
                } else {
                    JOptionPane.showMessageDialog(null, "El archivo no se pudo cargar");
                }
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrerActionPerformed
        System.out.println("sirve");
        String txt = jTALexico.getText();
        analizadorLexico.analizadorLexico(txt);
        lexemas.setModel(tablaLexemas(analizadorLexico.getListaLexema()));
        ArrayList<Lexema> lista = analizadorLexico.getListaLexema();
        analizadorSintactico.analisar(lista);
        File file = new File("C:\\Users\\Pepe\\Desktop\\Nueva carpeta\\AnalizadorLexico\\src\\recursos\\Archivo.html");
        Archivo a = analizadorSintactico.getArchivo();
        a.llenarHijos();
        arbolDerivacion.setModel(new DefaultTreeModel(a));
        analizadorSemantico_controlador.AnalizadorSemantico analisis = new AnalizadorSemantico();
        analisis.analizar(a);
        String documento = a.parse();
        String mensaje = cargar.GuardarArchivo(file, documento);
        if (mensaje != null) {
            JOptionPane.showMessageDialog(null, mensaje);
        }
        String url = "C:\\Users\\Pepe\\Desktop\\Nueva carpeta\\AnalizadorLexico\\src\\recursos\\Archivo.html";
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
            //System.out.println(a.parse());
            //errores.setModel(tablaErrorLexico(analizadorLexico.getListaErroresLexico()));
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCorrerActionPerformed

    /**
     * *
     * Metodo que se encarga de crear el modelo para cargar la tabla de lexemas
     * con la informacion que requiere mostrar
     *
     * @param listaLexemas
     * @return
     */
    public DefaultTableModel tablaLexemas(ArrayList<Lexema> listaLexemas) {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("#");
        model.addColumn("Lexema");
        model.addColumn("Tipo Lexema");
        model.addColumn("Token");
        model.addColumn("Fila");
        model.addColumn("Columna");

        for (int i = 0; i < listaLexemas.size(); i++) {
            model.addRow(new Object[]{
                (i + 1),
                listaLexemas.get(i).getLexema(),
                listaLexemas.get(i).getTipoLexema(),
                listaLexemas.get(i).getToken(),
                listaLexemas.get(i).getLinea(),
                listaLexemas.get(i).getColumna()
            });
        }

        return model;
    }

    /**
     * *
     * Metodo que se encarga de crear el metodo para cargar la tabla de errores
     * de lexema con la informacion que requiere mostrar
     *
     * @param listaErrorLexico
     * @return
     */
    public DefaultTableModel tablaErrorLexico(ArrayList<ErrorLexico> listaErrorLexico) {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("#");
        model.addColumn("Error");
        model.addColumn("Fila");
        model.addColumn("Columna");

        for (int i = 0; i < listaErrorLexico.size(); i++) {
            model.addRow(new Object[]{
                (i + 1),
                listaErrorLexico.get(i).getToken(),
                listaErrorLexico.get(i).getFila(),
                listaErrorLexico.get(i).getColumna()
            });
        }

        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolDerivacion;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCorrer;
    private javax.swing.JTextArea consola;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTALexico;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable lexemas;
    // End of variables declaration//GEN-END:variables
}
